name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: 'â• Adds'
    labels:
      - '/add.*/i'

  - title: 'â– Removes'
    labels:
      - '/del.*/i'
    
  - title: 'ğŸš€ Features'
    labels:
      - '/feat.*/i'
      - '/feature.*/i'
      - '/enhancement.*/i'

  - title: 'ğŸ› Fixes'
    labels:
      - '/fix.*/i'
      - '/bugfix.*/i'
      - '/bug.*/i'

  - title: 'ğŸ§ª Tests'
    labels:
      - '/test.*/i'

  - title: 'ğŸ§° Maintenance'
    labels: 
      - '/chore.*/i'
      - '/documentation.*/i'
      - '/doc.*/i'
      - '/dependencies.*/i'

change-template: | 
  $TITLE @$AUTHOR (#$NUMBER)
  $COMMITS

change-title-escapes: '\<*_&'

version-resolver:
  patch:
    labels:
      - 'release-patch'
  minor:
    labels:
      - 'release-minor'
  major:
    labels:
      - 'release-major'
  default: minor

template: |
  ## Whatâ€™s Changed

  $CHANGES
