name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: 'â• Adds'
    title:
      - '/add.*/i'
    labels:
      - 'add'

  - title: 'â– Removes'
    title:
      - '/del.*/i'
    labels:
      - 'del'
    
  - title: 'ğŸš€ Features'
    title:
      - '/feat.*/i'
      - '/feature.*/i'
      - '/enhancement.*/i'
    labels:
      - 'feat'
      - 'feature'
      - 'enhancement'

  - title: 'ğŸ› Fixes'
    title:
      - '/fix.*/i'
      - '/bugfix.*/i'
      - '/bug.*/i'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'

  - title: 'ğŸ§ª Tests'
    title:
      - '/test.*/i'
    labels:
      - 'test'

  - title: 'ğŸ§° Maintenance'
    title: 
      - '/chore.*/i'
      - '/documentation.*/i'
      - '/doc.*/i'
      - '/dependencies.*/i'
    labels:
      - 'chore'
      - 'documentation'
      - 'doc'
      - 'dependencies'

change-template: | 
  $TITLE @$AUTHOR (#$NUMBER)
  $COMMITS

change-title-escapes: '\<*_&'

version-resolver:
  patch:
    labels:
      - 'release-patch'
  minor:
    labels:
      - 'release-minor'
  major:
    labels:
      - 'release-major'
  default: minor

template: |
  ## Whatâ€™s Changed

  $CHANGES
