version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'

    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '19:00'
      timezone: 'Europe/Warsaw'

    commit-message:
      prefix: 'deps: '

    open-pull-requests-limit: 5

    groups:
      actions-group:
        patterns: ["*"]

    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]

  - package-ecosystem: 'docker'
    directory: '/'

    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '19:00'
      timezone: 'Europe/Warsaw'

    commit-message:
      prefix: 'deps: '

    open-pull-requests-limit: 3

  - package-ecosystem: 'gomod'
    directory: '/'

    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '19:00'
      timezone: 'Europe/Warsaw'

    commit-message:
      prefix: 'deps: '

    open-pull-requests-limit: 5

    groups:
      golang-ecosystem:
        patterns: ["*"]